---
- name: Ensure extra dnf packages are present
  ansible.builtin.dnf:
    name: "{{ extra_packages }}"
    state: present
  become: true

- name: Ensure extra flatpak remotes are present
  ansible.builtin.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
  become: true

- name: Ensure extra flatpak packages are present
  ansible.builtin.flatpak:
    name: "{{ extra_flatpak_packages }}"
    state: present
  become: true

  #- name: Retrieve the current user information
  #ansible.builtin.set_fact:
  #  current_user: "{{ ansible_env.USER }}"
  #when: install_kvm

- name: Ensure virtulization is configured
  become: true
  when: install_kvm
  block:
    - name: Ensure virtualization packages are present
      ansible.builtin.dnf:
        name: "{{ kvm_packages }}"
        state: present

    - name: Ensure that libvirtd is enabled and running
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

    - name: Ensure that current user is member of libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user|default(lookup('env','USER')) }}"
        groups: libvirt
        append: true
        state: present

    - name: Ensure that uri_default points to system
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user|default(lookup('env','USER')) }}/.config/libvirt/libvirt.conf"
        line: 'uri_default = "qemu:///system"'
        create: true
      become: false
